
import SideBar from "./components/sidebar";
import { Inter } from "next/font/google";
import { DataProvider } from "./helpers/data.js";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DataProvider>
    <html lang="en">
        <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </head>
      <body className={inter.className}>
        <div className="flex ">
        <SideBar />
        <div className="flex-1" >{children}</div>
        </div>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
        </body>
    </html>
    </DataProvider>
  );
}
